### ISSUE TITLE
std::meta::enumerators_of fails to be a constant expression

### ISSUE THREAD

**Issue by beached** [bloomberg/clang-p2996#103]
**Describe the bug**
`std::meta::enumerators_of` fails to be a constant expression
https://p2996.godbolt.org/z/5jcGaaodd

compiled with `clang++ -std=c++26 -freflection-latest`
```cpp
#include <experimental/meta>
#include <print>
#include <type_traits>

template <typename E>
    requires std::is_enum_v<E>
constexpr std::string_view enum_to_string(E value) {
    template for (constexpr auto enumerator : std::meta::enumerators_of(^^E)) {
        if (value == [:enumerator:]) {
            return std::meta::identifier_of(enumerator);
        }
    }
    return std::string_view{};
}

enum class Foo { AChoo, BlessYou };

int main() { std::println("{}", enum_to_string(Foo::AChoo)); }
```

```
<source>:8:47: error: constexpr variable '[, , , , , ]' must be initialized by a constant expression
    8 |     template for (constexpr auto enumerator : std::meta::enumerators_of(^^E)) {
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<source>:18:33: note: in instantiation of function template specialization 'enum_to_string<Foo>' requested here
   18 | int main() { std::println("{}", enum_to_string(Foo::AChoo)); }
      |                                 ^
<source>:8:47: note: pointer to subobject of heap-allocated object is not a constant expression
    8 |     template for (constexpr auto enumerator : std::meta::enumerators_of(^^E)) {
      |                                               ^
/opt/compiler-explorer/clang-bb-p2996-trunk-20241013/bin/../include/c++/v1/__memory/allocator.h:101:32: note: heap allocation performed here
  101 |       return static_cast<_Tp*>(::operator new(__n * sizeof(_Tp)));
      |                                ^
<source>:8:47: error: cannot decompose private member '__begin_' of 'std::vector<meta::info>'
    8 |     template for (constexpr auto enumerator : std::meta::enumerators_of(^^E)) {
      |          
```

**Expected behavior**
`std::meta::enumerators_of` works in constant expressions

**Comment by katzdm** [comment]
Hey @beached ! We currently support two out of the three "forms" of expansion statements proposed by P1306.
* Expansion over _expansion-init-lists_ (e.g., `template for (auto e : {1, 'a', true})`), and
* Expansion over _destructurable_ expressions (e.g., `template for (auto e : make_tuple(1, 'a', true))`).

Two unfortunate bits:
1. We don't yet support expansion over _iterable_ expressions (though I hope to implement this in the next few weeks), and
2. P1306 is likely to see a revision that will require the iterable expression to be a constant expression.

Since a non-empty vector isn't a permitted result of a constant expression (due to its designation of dynamically-allocated memory), that means that `template for (constexpr auto e : enumerators_of(^^E))` won't quite work as-is. That said, there's another function proposed by P2996, `define_static_array`, that lets us work around the issue. So once I implement expansion over iterable expressions, you should be able to write:

```cpp
template for (constexpr auto enumerator : std::meta::define_static_array(enumerators_of(^^E))
```

Until then, the `expand` workaround from P2996 should work here. Hope that helps!

**Comment by beached** [comment]
thank you
