### ISSUE TITLE
std::meta::bases_of returns broken info objects

### ISSUE THREAD

**Issue by ilazaric** [bloomberg/clang-p2996#16]
Elements of `std::meta::bases_of(<reflection-of-a-class>)` do not satisfy `std::meta::is_type`

https://godbolt.org/z/abaEq5zob

```
#include <experimental/meta>

struct A {};
struct C : A {};

// fails
static_assert(std::meta::is_type(std::meta::bases_of(^C)[0]));
```

**Comment by katzdm** [comment]
Hey, @ilazaric ! This is a bit of a confusing case in 2996, but `bases_of(^C)` does not return the collection of types from which `C` inherits, but rather the set of "base class specifiers" from the definition of `C`. That is, an object in that set refers to a declaration like `: public A`, not to `A` itself - this is an important point, since we don't want to "lose track" of the information that `A` is public (or virtual, etc) or else we can't implement queries related to the "kind of inheritance" that `C` has from `A`.

While we could of course implement `is_type(bases_of(C)[0])` to be true, that would give the impression that you can splice it as a type. You cannot, and we want to keep the operation of splicing a reflection of a base class specifier ill-formed for the moment to allow for future extension.

That said, fixing your example is thankfully straightforward:

```cpp
#include <experimental/meta>

struct A {};
struct C : A {};

static_assert(is_type(type_of(bases_of(^C)[0])));
```

**Comment by ilazaric** [comment]
> That is, an object in that set refers to a declaration like : public A, not to A itself - this is an important point, since we don't want to "lose track" of the information that A is public (or virtual, etc) or else we can't implement queries related to the "kind of inheritance" that C has from A.

I thought the filters were for that, so you'd do something like `bases_of(^C, is_public)`

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2996r2.html#members_of-static_data_members_of-nonstatic_data_members_of-bases_of-enumerators_of-subobjects_of
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2996r2.html#pnum_97
The proposal says that `bases_of` returns "reflections of all the direct base classes"
That specific wording to me sounds like one would expect the elements to be types, since classes are types
It might be better to say "base class specifiers"?

To be clear, I am perfectly fine with the approach you described, it just seems a bit ambiguous in the paper atm

**Comment by katzdm** [comment]
Agreed, I think we need to clarify the wording of the paper. Appreciate the feedback!
