### ISSUE TITLE
Reflection syntax may be incompatible with OpenMP

### ISSUE THREAD

**Issue by tambry** [bloomberg/clang-p2996#33]
Similar to ObjC's `-fblocks` OpenCL supports blocks started by `^`. [This](https://github.com/bloomberg/clang-p2996/blob/843fd93cfa1da4e493815f48d1a4d8a7d9bb6470/clang/lib/Frontend/CompilerInvocation.cpp#L616) check should check `LangOpts.Blocks` instead.  
OpenMP pragmas use syntax such as `+:argv[0][:1]` so a `|| LangOpts.OpenMP` should also be added.

**Comment by katzdm** [comment]
Hey @tambry ! Thanks for the bug report.

> [This](https://github.com/bloomberg/clang-p2996/blob/843fd93cfa1da4e493815f48d1a4d8a7d9bb6470/clang/lib/Frontend/CompilerInvocation.cpp#L616) check should check `LangOpts.Blocks` instead.

Agreed.

> OpenMP pragmas use syntax such as `+:argv[0][:1]`

I'm aware of the OpenMP case, but what I'm less clear on (due to limited familiarity with OpenMP) it would be sensible for splices to ever appear in OpenMP pragmas - if not, this could maybe be handled by parsing the `[:` and `:]` tokens differently when in the context of an OpenMP pragma. If you have an OpenMP background, I'd appreciate any insight you can share here!

**Comment by tambry** [comment]
Unfortunately I don't have an OpenMP background so can't help with that. 😞

**Comment by katzdm** [comment]
No worries - I've adopted your suggested `LangOpts.Blocks` change. For the time being, I'll change this issue name to reflect the uncertain conflict with OpenMP, and will seek further clarification.

**Comment by katzdm** [comment]
We'll be adopting a different syntax for P2996, likely in the next (R6) revision.
