### ISSUE TITLE
Cannot use `reflect_invoke` metafunction to invoke a member function

### ISSUE THREAD

**Issue by katzdm** [bloomberg/clang-p2996#5]
Given a reflection `RMemFn`, of a member function `Cls::MemFn`, a reflection `RObj` of a constant value `Obj` having type either `Cls` or `Cls *`, and reflections `R_0, ..., R_n` of constant values `a_0, ..., a_n`: if either `obj.F(a_0, ..., a_n)` or `obj->F(a_0, ..., a_n)` is a well-formed constant expression not returning `void`, then it would be nice to be able to obtain a reflection of the resulting value by calling
```cpp
constexpr auto R = reflect_invoke(RMemFn, RObj, R_0, ..., R_n);
```

**Comment by BaLiKfromUA** [comment]
I am looking into it. Will try to deliver it.

Am I understand it right, that, probably, we are interested in introducing one more overload of `reflect_invoke` to separate case of non-static member function?

so instead of 
```
constexpr auto R = reflect_invoke(RMemFn, RObj, R_0, ..., R_n);
```

it could look like this
```
constexpr auto R = reflect_invoke(RMemFn, RObj, {R_0, ..., R_n});
```

Similar to what you have in p2996r3 for template functions but without list as a second parameter

**Comment by katzdm** [comment]
Not quite - if the reflection represents a member function, then the first argument will be the object which the function is invoked on.

**Comment by BaLiKfromUA** [comment]
Implemented first version of disscussed functionality, please review when you have time.

I suspect that more validation should be added (e.g. check that method is not special) into my code but would like to disscuss it in scope of initial review.
