### ISSUE TITLE
call to immediate function is not a constant expression

### ISSUE THREAD

**Issue by Yaraslaut** [bloomberg/clang-p2996#62]
I stumbled in weird compiler error, code in question : https://godbolt.org/z/Yox46WPMd 
in short 
```
constexpr auto reflA = ^A;
form::util::printMembers<[:reflA:]>(); // <------ works
constexpr auto refl = CreateClass<CreateUniqueT<int>>();
form::util::printMembers<[:refl:]>(); // <---  error: call to immediate function 'form::util::printMembers<CreateUniqueT<int, (lambda at <source>:97:45)>>' is not a constant expression
```

**Comment by katzdm** [comment]
Hey @Yaraslaut - Here is what's happening.
- Your `form::util::name_of` function returns a `std::string`, which necessarily allocates some memory from dynamic storage (i.e., to hold its value).
- Dynamic memory allocated by a constant expression must be deallocated in the course of its evaluation.
- This means that `form::util::name_of(^anything)` can never itself be a constant expression (though it may appear in the evaluation of one).
- You call `form::util::name_of(^T)` in your implementation of `constexpr void printMembers()`. The compiler looks to see whether `form::util::name_of(^T)` is a subexpression of a larger constant expression, but finds that it isn't one (i.e., because `std::println` is not constexpr).
- The compiler therefore concludes that the "runtime path" of the `constexpr` function of which the call is a part is ill-formed, and "promotes" the function to effectively be `consteval`.
- But the "consteval path" for the function is _also_ ill-formed, because `std::println` is not constexpr. So all it can do is diagnose an error.

Based on the above, I believe the issue is with your example - I'm going to close, but please re-open if I've missed something!

**Comment by Yaraslaut** [comment]
Thanks @katzdm  for the detailed explanation, I indeed forgot that I changed the signature of `name_of` and if i keep string_view than everything is fine, thanks. I am still a bit confused why it is working for declared type, but not for defined through `define_class` call

**Comment by katzdm** [comment]
Ah! Good point, and the reason is actually pretty fun - libcxx implements a "short string optimization" in the `std::string` implementation, which stores small strings in a static buffer. In the case of the compiler running on godbolt, as many as (but no more than) [22 characters](https://godbolt.org/z/q9T4ezTff) (including the null terminator) can be stored before a dynamic allocation occurs. The name rendered for `CreateUniqueT<int, (lambda at /app/example.cpp:96:45)>` is what overruns that 22 character limit, thus triggering a dynamic allocation and rendering the call not-constexpr.

All of that said, there _is_ a subtle bug here: the name returned by `name_of` here should just be `CreateUniqueT`; the P2996 spec states that `name_of` should not include the names of template arguments.
