### ISSUE TITLE
Inconsistency in evaluation of `identifier_of` as constant expressions

### ISSUE THREAD

**Issue by Shuangcheng-Ni** [bloomberg/clang-p2996#98]
Suppose `arr` is an array of `std::meta::info` and `arr[0]` is `^std::string`. `identifier_of(arr[0])` will cause an error (`call to consteval function 'std::meta::identifier_of' is not a constant expression`), while `identifier_of(^std::string)` compiles successfully. Is this the intended behavior?

See [godbolt](https://godbolt.org/z/PzjGhqEaK) line 42-43.

**Comment by katzdm** [comment]
Hey @Shuangcheng-Ni ! This is actually working as intended - When you use `std::string` as a template argument for `get_unique_types`, the type alias is "lost", and it decays to `std::basic_string<char, std::allocator<char>>`. `identifier_of(^^std::basic_string<char, std::allocator<char>>)` isn't a constant expression, because its name isn't an identifier.

You could probably make this work by passing reflections into `get_unique_types` rather than passing the types directly, since (top level) aliases are preserved by reflection.
